spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gallery
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
